name: 'Run Danger Action'
on:
  pull_request:
jobs:
  run-danger-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Installing dependencies
        run: npm install --legacy-peer-deps 
      - name: install yarn
        run: npm install -g yarn
      - name: Danger
        run: yarn danger ci
        env: 
          GITHUB_TOKEN: ${{ github.token }}